### ISSUE TITLE
Exception: Unknown end file token

### ISSUE THREAD

**Issue by yilu1015** [johndoe31415/pdfminify#11]
Is this an issue with my PDF? Thanks for looking into the problem.

```
pdfminify /Users/abc/Coding/minimize-pdf/raw/uva.x030262661.pdf /Users/abc/Coding/minimize-pdf/output/uva.x030262661.pdf
Traceback (most recent call last):
  File "/Users/abc/.pyenv/versions/venv-3.8.8/bin/pdfminify", line 33, in <module>
    sys.exit(load_entry_point('pdfminify==0.2.1', 'console_scripts', 'pdfminify')())
  File "/Users/abc/.pyenv/versions/venv-3.8.8/bin/pdfminify", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Users/abc/.pyenv/versions/3.8.8/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/Users/abc/.pyenv/versions/3.8.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/abc/.pyenv/versions/3.8.8/envs/venv-3.8.8/lib/python3.8/site-packages/pdfminify/__main__.py", line 139, in <module>
    pdf = llpdf.PDFReader().read(args.infile)
  File "/Users/abc/.pyenv/versions/3.8.8/envs/venv-3.8.8/lib/python3.8/site-packages/llpdf/PDFReader.py", line 138, in read
    self._read_pdf_body(f, pdf)
  File "/Users/abc/.pyenv/versions/3.8.8/envs/venv-3.8.8/lib/python3.8/site-packages/llpdf/PDFReader.py", line 54, in _read_pdf_body
    self._read_endfile(f, pdf)
  File "/Users/abc/.pyenv/versions/3.8.8/envs/venv-3.8.8/lib/python3.8/site-packages/llpdf/PDFReader.py", line 98, in _read_endfile
    raise Exception("Unknown end file token '%s' at offset 0x%x." % (line, f.tell()))
Exception: Unknown end file token 'trailer << /Info 1673 0 R /Root 1675 0 R /Size 1680 /Prev 296948963             /ID [<86d42d9901d247352606bc033625d3d7><86d42d9901d247352606bc033625d3d7>] >>' at offset 0x1fa.
```

**Comment by johndoe31415** [comment]
Hmmmmmmmm. This looks like a valid PDF trailer. It's location is odd (0x1fa is at the very beginning, would expect this to be towards the end), but I'm not sure why it cannot parse it. Could you provide the PDF for testing?

**Comment by yilu1015** [comment]
[test.pdf](https://github.com/johndoe31415/pdfminify/files/6683122/test.pdf)
Thanks for looking into this issue!
