### ISSUE TITLE
AttributeError: 'list' object has no attribute 'objid'

### ISSUE THREAD

**Issue by yilu1015** [johndoe31415/pdfminify#12]
```
(venv-3.8.8) MacBook-Pro:Downloads abc$ pdfminify carr.pdf carr-out.pdf
Traceback (most recent call last):
  File "/Users/abc/.pyenv/versions/venv-3.8.8/bin/pdfminify", line 33, in <module>
    sys.exit(load_entry_point('pdfminify==0.2.1', 'console_scripts', 'pdfminify')())
  File "/Users/abc/.pyenv/versions/venv-3.8.8/bin/pdfminify", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Users/abc/.pyenv/versions/3.8.8/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/Users/abc/.pyenv/versions/3.8.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/abc/.pyenv/versions/3.8.8/envs/venv-3.8.8/lib/python3.8/site-packages/pdfminify/__main__.py", line 148, in <module>
    pdf_filter.run()
  File "/Users/abc/.pyenv/versions/3.8.8/envs/venv-3.8.8/lib/python3.8/site-packages/llpdf/filters/DownscaleImageOptimization.py", line 72, in run
    for (page_obj, page_content) in self._pdf.parsed_pages:
  File "/Users/abc/.pyenv/versions/3.8.8/envs/venv-3.8.8/lib/python3.8/site-packages/llpdf/PDFDocument.py", line 138, in parsed_pages
    content = self.lookup(content_xref)
  File "/Users/abc/.pyenv/versions/3.8.8/envs/venv-3.8.8/lib/python3.8/site-packages/llpdf/PDFDocument.py", line 148, in lookup
    return self[(xref.objid, xref.gennum)]
AttributeError: 'list' object has no attribute 'objid'
```

**Comment by johndoe31415** [comment]
Hey, thanks for the report. No chance to reproduce without the PDF, tough. Could you provide the PDF for testing?

**Comment by yilu1015** [comment]
Thanks for looking into this. I downloaded the PDF from this site: https://b-ok.cc/book/2758147/7b18dd
