### ISSUE TITLE
ModuleNotFoundError: No module named 'parser'

### ISSUE THREAD

**Issue by andit** [johndoe31415/pdfminify#15]
### What is the issue?

Hi, I've installed
pip install llpdf  
and 
pip install pdfminify   
and when I call in my python console (in PyCharm) 
PS V:\Python\AG_Toolbox\DEV> pdfminify -h

I got these error:
Traceback (most recent call last):
  File "C:\Users\taan\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\taan\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "\\sbs\ATS-EDV\Python\AG_Toolbox\DEV\venv\Scripts\pdfminify.exe\__main__.py", line 4, in <module>
  File "v:\python\ag_toolbox\dev\venv\lib\site-packages\pdfminify\__main__.py", line 28, in <module>
    import llpdf
  File "v:\python\ag_toolbox\dev\venv\lib\site-packages\llpdf\__init__.py", line 23, in <module>
    import llpdf.filters
  File "v:\python\ag_toolbox\dev\venv\lib\site-packages\llpdf\filters\__init__.py", line 23, in <module>
    from .DownscaleImageOptimization import DownscaleImageOptimization
  File "v:\python\ag_toolbox\dev\venv\lib\site-packages\llpdf\filters\DownscaleImageOptimization.py", line 27, in <module>
    from llpdf.types.PDFObject import PDFObject
  File "v:\python\ag_toolbox\dev\venv\lib\site-packages\llpdf\types\PDFObject.py", line 24, in <module>
    from llpdf.repr import PDFParser
  File "v:\python\ag_toolbox\dev\venv\lib\site-packages\llpdf\repr\PDFParser.py", line 24, in <module>
    from . import tpg
  **File "v:\python\ag_toolbox\dev\venv\lib\site-packages\llpdf\repr\tpg.py", line 54, in <module>
    import parser
ModuleNotFoundError: No module named 'parser'**

What can I do to solve it?

Python 3.10
llpdf 0.0.4
pdfminify 0.2.1

Best Regards

Andi

### All Info Provided

- [X] I have described the exact command line I was using
- [X] I have included the version number of pdfminify I'm using
- [X] I have attached an example PDF that exhibits the issue

**Comment by johndoe31415** [comment]
Hey there. It appears the "parser" module was removed from Python 3.10.

tpg is one of the few dependencies I have and I am not competent of fixing it myself. I've filed an issue with TPG here: https://github.com/CDSoft/tpg/issues/1 but not sure that this is going to be an easy thing.

For now, my suggestion would be to use Python 3.9 :-(

**Comment by andit** [comment]
thanks for the speedy reply.

Danke, Andi :)

**Comment by andit** [comment]
... btw. can you give me an example how to use it within python?
is there something like

import pdfminify as pdfminify
pdf = pdfminify.pdfminify(pdf_in="srcfile.pdf", pdf_out="destfile.pdf", jpeg-quality=40)

Best Regards

Andi

**Comment by johndoe31415** [comment]
I've just released llpdf v0.0.5 which should fix your issue.

There's really no "easy" was to run pdfminify from Python, but the __main__.py is fairly simple in its structure and should give you an indication of what you can do (instanciate a PDFreader, run it through some filters, PDFwriter). Closing this as fixed.
