### ISSUE TITLE
IndexError: bytearray index out of range

### ISSUE THREAD

**Issue by yatrik-cloud** [johndoe31415/pdfminify#16]
### What is the issue?

I have just given two arguments, still encountered this error.
Even though I have tried changing the input pdf files, still facing the same issue.
Kindly address it.

pdfminify version 0.2.1; llpdf version: 0.0.5

(venv) PS D:\python_projects\pdf compression r&D\venv\Scripts> pdfminify "D:\python_projects\pdf compression r&D\66page.pdf" "D:\python_projects\pdf compression r&D\out.pdf"
Traceback (most recent call last):
  File "D:\python_projects\pdf compression r&D\venv\Scripts\pdfminify-script.py", line 33, in <module>
    sys.exit(load_entry_point('pdfminify==0.2.1', 'console_scripts', 'pdfminify')())
  File "D:\python_projects\pdf compression r&D\venv\Scripts\pdfminify-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Users\Yatrik.s\AppData\Local\Programs\Python\Python310\lib\importlib\metadata\__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "C:\Users\Yatrik.s\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\python_projects\pdf compression r&D\venv\lib\site-packages\pdfminify\__main__.py", line 139, in <module>
    pdf = llpdf.PDFReader().read(args.infile)
  File "D:\python_projects\pdf compression r&D\venv\lib\site-packages\llpdf\PDFReader.py", line 133, in read
    hdr_version = self._read_identifying_header(f)
  File "D:\python_projects\pdf compression r&D\venv\lib\site-packages\llpdf\PDFReader.py", line 40, in _read_identifying_header
    if (after_hdr[0] != ord("%")) or any(value & 0x80 != 0x80 for value in after_hdr[ 1 : 5 ]):
IndexError: bytearray index out of range

### All Info Provided

- [X] I have described the exact command line I was using
- [X] I have included the version number of pdfminify I'm using
- [X] I have attached an example PDF that exhibits the issue

**Comment by AhmedThahir** [comment]
Same issue I'm facing. Any updates?

**Comment by johndoe31415** [comment]
The reason the third checkbox in "All Info Provided"

![image](https://github.com/johndoe31415/pdfminify/assets/5919339/ae08dbc5-b59e-4403-a7d2-a37168f1185b)

is there is because without a PDF to test it, I am completely unable to reproduce the error. As such, there's nothing I can do to even replicate the issue.
