### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by altblue** [johndoe31415/pdfminify#4]
Hi
I was not able to test your project with a [„blank” pdf](https://github.com/johndoe31415/pdfminify/files/2356530/output.pdf):

```
$ git clone --depth=1 https://github.com/johndoe31415/pdfminify.git
Cloning into 'pdfminify'...
remote: Counting objects: 93, done.
remote: Compressing objects: 100% (90/90), done.
remote: Total 93 (delta 24), reused 21 (delta 1), pack-reused 0
Unpacking objects: 100% (93/93), done.

$ cd pdfminify

$ head -1 pdfminify 
#!/usr/bin/python3

$ /usr/bin/python3 --version
Python 3.6.6

$ identify --version
Version: ImageMagick 6.9.9-38 Q16 x86_64 2018-03-12 http://www.imagemagick.org
Copyright: © 1999-2018 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC Modules OpenMP 
Delegates (built-in): bzlib cairo djvu fftw fontconfig freetype gslib jbig jng jp2 jpeg lcms ltdl lzma openexr pangocairo png ps rsvg tiff webp wmf x xml zlib

$ convert --version
Version: ImageMagick 6.9.9-38 Q16 x86_64 2018-03-12 http://www.imagemagick.org
Copyright: © 1999-2018 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC Modules OpenMP 
Delegates (built-in): bzlib cairo djvu fftw fontconfig freetype gslib jbig jng jp2 jpeg lcms ltdl lzma openexr pangocairo png ps rsvg tiff webp wmf x xml zlib

$ chromium-browser --disable-gpu --headless --print-to-pdf about:blank
[0906/130603.484385:ERROR:gpu_process_transport_factory.cc(1016)] Lost UI shared context.
[0906/130603.998146:INFO:headless_shell.cc(590)] Written to file output.pdf.

$ pdfinfo output.pdf 
Creator:        Chromium
Producer:       Skia/PDF m68
CreationDate:   Thu Sep  6 13:06:03 2018 EEST
ModDate:        Thu Sep  6 13:06:03 2018 EEST
Tagged:         no
UserProperties: no
Suspects:       no
Form:           none
JavaScript:     no
Pages:          1
Encrypted:      no
Page size:      612 x 792 pts (letter)
Page rot:       0
File size:      23838 bytes
Optimized:      no
PDF version:    1.4

$ ./pdfminify output.pdf mini.pdf
Traceback (most recent call last):
  File "./pdfminify", line 141, in <module>
    pdf = llpdf.PDFFile(infile)
  File "/tmp/pdfminify/llpdf/PDFFile.py", line 47, in __init__
    self._read_pdf()
  File "/tmp/pdfminify/llpdf/PDFFile.py", line 229, in _read_pdf
    self._read_endfile()
  File "/tmp/pdfminify/llpdf/PDFFile.py", line 194, in _read_endfile
    line = self._read_textline().strip("\r\n ")
  File "/tmp/pdfminify/llpdf/PDFFile.py", line 181, in _read_textline
    line = self._f.readline_nonempty().decode("ascii").rstrip("\r\n")
  File "/tmp/pdfminify/llpdf/FileRepr.py", line 129, in readline_nonempty
    line = self.readline()
  File "/tmp/pdfminify/llpdf/FileRepr.py", line 124, in readline
    (data, terminal) = self.read_until([ b"\r\n", b"\n", b"\r" ])
TypeError: 'NoneType' object is not iterable
```

Is there anything I can do to make it work
or at least to help debugging the issue?

Thanks!

**Comment by johndoe31415** [comment]
Hey @altblue -- thanks for the hands down best bug report I ever got :-) Absolutely perfect, all the info I need is contained and I quickly checked and can confirm the issue. The root cause is that the generated PDF doesn't have a terminating character after the final "%%EOF" (i.e., no newline), causing it to die that way. However, even after "fixing" the PDF, there's other issues with that demo PDF that need to be addressed. I'll take a peek in the evening today and see if I can help you out.

Again, thanks for the super verbose bug report.

**Comment by johndoe31415** [comment]
Issue isn't fully fixed yet, see commit message.
