### ISSUE TITLE
Syntax error near /Page

### ISSUE THREAD

**Issue by mbarkhau** [johndoe31415/pdfminify#7]
I get an error processing [this file](https://www.dropbox.com/s/p7h0q2g41qwxn61/testfile.pdf?dl=0), which was generated using WeasyPrint.

```
$ ./pdfminify ../WeasyPrint/testfile.pdf ../WeasyPrint/testfile_min.pdf
------------------------------------------------------------------------------------------------------------------------
<< /Type /Page % 1
   /Parent 1 0 R
   /MediaBox [ 0 0 595 841 ]
   /Contents 4 0 R
   /Group <<
      /Type /Group
      /S /Transparency
      /I true
      /CS /DeviceRGB
   >>
   /Resources 3 0 R
>>

------------------------------------------------------------------------------------------------------------------------
<< /Type /Page % 1
...
Traceback (most recent call last):
  File "./pdfminify", line 141, in <module>
    pdf = llpdf.PDFFile(infile)
  File "/home/mbarkhau/workspace/pdfminify/llpdf/PDFFile.py", line 47, in __init__
    self._read_pdf()
  File "/home/mbarkhau/workspace/pdfminify/llpdf/PDFFile.py", line 224, in _read_pdf
    objcnt = self._read_objects()
  File "/home/mbarkhau/workspace/pdfminify/llpdf/PDFFile.py", line 158, in _read_objects
    obj = PDFObject.parse(self._f)
  File "/home/mbarkhau/workspace/pdfminify/llpdf/types/PDFObject.py", line 141, in parse
    return cls(objid = objid, gennum = gennum, rawdata = object_data)
  File "/home/mbarkhau/workspace/pdfminify/llpdf/types/PDFObject.py", line 60, in __init__
    self._content = PDFParser.parse(content)
  File "/home/mbarkhau/workspace/pdfminify/llpdf/repr/PDFParser.py", line 108, in parse
    return ParseTools.parse_using(text, PDFParser)
  File "/home/mbarkhau/workspace/pdfminify/llpdf/repr/ParseTools.py", line 58, in parse_using
    result = parser(text)
  File "/home/mbarkhau/workspace/pdfminify/llpdf/repr/tpg.py", line 942, in __call__
    return self.parse('START', input, *args, **kws)
  File "/home/mbarkhau/workspace/pdfminify/llpdf/repr/tpg.py", line 1125, in parse
    return Parser.parse(self, axiom, input, *args, **kws)
  File "/home/mbarkhau/workspace/pdfminify/llpdf/repr/tpg.py", line 969, in parse
    raise SyntacticError((line, column), "Syntax error near %s"%last_token)
llpdf.repr.tpg.SyntacticError: SyntacticError at line 1, column 10: Syntax error near /Page
```

**Comment by johndoe31415** [comment]
Hi @mbarkhau -- the same reason applies as discussed with #6.

For your issue, the comment seems to be causing trouble to the pdfminify parser. I'll see if I can quickly fix this, although I'm not sure about it.
