### ISSUE TITLE
KeyError: Name</ColorSpace>

### ISSUE THREAD

**Issue by eeezae** [johndoe31415/pdfminify#9]
![image](https://user-images.githubusercontent.com/34007837/118446400-2c018400-b722-11eb-97a9-e1f388f95e2f.png)

```
      llpdf.PDFReader [W]: PDF seems to violate standard, bytes read in second line are bytearray(b'1 0 obj').
 llpdf.filters.DownscaleImageOptimization [W]: Ignoring unsupported image XRef<25, 0>: Cannot generate PDFImage object with non-trivial value decode array: [0, 1, 0, 1, 0, 1, 0, 1]
 llpdf.filters.DownscaleImageOptimization [W]: Ignoring unsupported image XRef<26, 0>: Cannot generate PDFImage object with non-trivial value decode array: [0, 1, 0, 1, 0, 1, 0, 1]
 llpdf.filters.DownscaleImageOptimization [W]: Ignoring unsupported image XRef<27, 0>: Cannot generate PDFImage object with non-trivial value decode array: [0, 1, 0, 1, 0, 1, 0, 1]
Traceback (most recent call last):
  File "/Users/mc/opt/anaconda3/bin/pdfminify", line 5, in <module>
    from pdfminify.__main__ import main
  File "/Users/mc/opt/anaconda3/lib/python3.8/site-packages/pdfminify/__main__.py", line 148, in <module>
    pdf_filter.run()
  File "/Users/mc/opt/anaconda3/lib/python3.8/site-packages/llpdf/filters/DownscaleImageOptimization.py", line 79, in run
    image = self._pdf.get_image(img_xref)
  File "/Users/mc/opt/anaconda3/lib/python3.8/site-packages/llpdf/PDFDocument.py", line 266, in get_image
    image = PDFImage.create_from_object(image, alpha_channel)
  File "/Users/mc/opt/anaconda3/lib/python3.8/site-packages/llpdf/img/PDFImage.py", line 87, in create_from_object
    image = cls.create_raw_from_object(xobj)
  File "/Users/mc/opt/anaconda3/lib/python3.8/site-packages/llpdf/img/PDFImage.py", line 61, in create_raw_from_object
    colorspace_info = xobj.content[PDFName("/ColorSpace")]
KeyError: Name</ColorSpace>
```

**Comment by johndoe31415** [comment]
Hey there, thanks for the bug report. Any chance you can share the PDF so I can take a look?

**Comment by eeezae** [comment]
https://drive.google.com/file/d/1qGZ7pPRmtYlzxxt-Te13pGVLyT93n6Sm/view?usp=sharing

**Comment by johndoe31415** [comment]
Thanks a bunch! I can reproduce your error. Will look into this issue after my work day. Take care!
